export const theme = {
  // Theme styling goes here
  text: {
    bold: "font-bold",
    italic: "italic",
  },
  heading: {
    h1: "text-4xl font-bold",
    h3: "text-2xl font-bold",
  },
  link: "underline italic text-blue-500 cursor-pointer",
  code: "editor-code",
  quote:
    "ml-[20px] text-white-primary border-l-[6px] border-brand-primary pl-[12px] italic",
  list: {
    ol: "list-decimal p-0 m-0 ml-4",
    ul: "list-disc p-0 m-0 ml-4",
    listitem: "m-[8px_32px_8px_32px]",
  },
  codeHighlight: {
    atrule: "editor-tokenAttr",
    attr: "editor-tokenAttr",
    boolean: "editor-tokenProperty",
    builtin: "editor-tokenSelector",
    cdata: "editor-tokenComment",
    char: "editor-tokenSelector",
    class: "editor-tokenFunction",
    "class-name": "editor-tokenFunction",
    comment: "editor-tokenComment",
    constant: "editor-tokenProperty",
    deleted: "editor-tokenProperty",
    doctype: "editor-tokenComment",
    entity: "editor-tokenOperator",
    function: "editor-tokenFunction",
    important: "editor-tokenVariable",
    inserted: "editor-tokenSelector",
    keyword: "editor-tokenAttr",
    namespace: "editor-tokenVariable",
    number: "editor-tokenProperty",
    operator: "editor-tokenOperator",
    prolog: "editor-tokenComment",
    property: "editor-tokenProperty",
    punctuation: "editor-tokenPunctuation",
    regex: "editor-tokenVariable",
    selector: "editor-tokenSelector",
    string: "editor-tokenSelector",
    symbol: "editor-tokenProperty",
    tag: "editor-tokenProperty",
    url: "editor-tokenOperator",
    variable: "editor-tokenVariable",
  },
};
